sudo: required

services:
  - docker

language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules

#env:
#- TRUFFLE_DEVELOP_HOST=truffle TRUFFLE_DEVELOP_PORT=9545 TRUFFLE_COVERAGE_HOST=truffle-coverage TRUFFLE_COVERAGE_PORT=8555

before_install:
  - pwd
  - chmod +x ./scripts/testrpc_setup.sh
  - ./scripts/testrpc_setup.sh
  - npm install
  #- docker-compose up -d
  #- docker-compose --version
  #- docker-compose ps

script:
  #- docker-compose exec truffle-coverage env CONTINUOUS_INTEGRATION=true TRAVIS=true TRAVIS_JOB_ID="$TRAVIS_JOB_ID" TRAVIS_BRANCH="$TRAVIS_BRANCH" TRAVIS_PULL_REQUEST="$TRAVIS_PULL_REQUEST" scripts/coverage_run.sh
  #- docker-compose exec truffle truffle migrate
  #- docker-compose exec truffle truffle test
   - ./node_modules/.bin/truffle compile --all
   - ./node_modules/.bin/truffle migrate
   - ./node_modules/.bin/truffle test
   - chmod +x ./scripts/coverage_run.sh
   - ./scripts/coverage_run.sh
